In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[["classification_yes"]]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB

param_grid = {} 

grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')  
grid.fit(X_train, y_train) 

re=grid.cv_results_
grid_predictions = grid.predict(X_test) 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
print("The confusion Matrix:\n",cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print("The report:\n",clf_report)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
The confusion Matrix:
 [[51  0]
 [ 1 81]]
The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

The f1_macro value for best parameter {}: 0.9924946382275899

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [34]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9997608799617408

In [29]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.017418,0.005975,0.034103,0.011536,{},1.0,1.0,0.962573,0.981031,1.0,0.988721,0.014997,1

In [30]:
import pickle
filename="Final_model_NBC.sav"
pickle.dump(grid,open(filename,'wb'))

In [31]:
load_model=pickle.load(open("Final_model_NBC.sav",'rb'))
age=float(input("Age:"))
bp=float(input("bp:"))
al=float(input("al:"))
su=float(input("su:"))
bgr=float(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
sod=float(input("sod:"))
pot=float(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=int(input("sg_b 0 or 1:"))
sg_c=int(input("sg_c 0 or 1:"))
sg_d=int(input("sg_d 0 or 1:"))
sg_e=int(input("sg_e 0 or 1:"))
rbc_normal=int(input("rbc_normal 0 or 1:"))
pc_normal=int(input("pc_normal 0 or 1:"))
pcc_present=int(input("pcc_present 0 or 1:"))
ba_present=int(input("ba_present 0 or 1:"))
htn_yes=int(input("htn_yes 0 or 1:"))
dm_yes=int(input("dm_yes 0 or 1:"))
cad_yes=int(input("cad_yes 0 or 1:"))
appet_yes=int(input("appet_yes 0 or 1:"))
pe_yes=int(input("pe_yes 0 or 1:"))
ane_yes=int(input("ane_yes 0 or 1:"))

Age:26
bp:80
al:1
su:0
bgr:99
bu:22
sc:2.5
sod:135
pot:4.4
hrmo:15
pcv:40
wc:8600
rc:5.4
sg_b 0 or 1:1
sg_c 0 or 1:0
sg_d 0 or 1:0
sg_e 0 or 1:0
rbc_normal 0 or 1:0
pc_normal 0 or 1:0
pcc_present 0 or 1:1
ba_present 0 or 1:1
htn_yes 0 or 1:1
dm_yes 0 or 1:0
cad_yes 0 or 1:0
appet_yes 0 or 1:0
pe_yes 0 or 1:1
ane_yes 0 or 1:1

In [32]:
Future_Prediction=grid.predict([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,
       pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]